/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using order.Client;
using order.Api;
// uncomment below to import models
//using order.Model;

namespace order.Test.Api
{
    /// <summary>
    ///  Class for testing OrderApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OrderApiTests : IDisposable
    {
        private OrderApi instance;

        public OrderApiTests()
        {
            instance = new OrderApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OrderApi
            //Assert.IsType<OrderApi>(instance);
        }

        /// <summary>
        /// Test ApproveOrder
        /// </summary>
        [Fact]
        public void ApproveOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderApproveOrderRequest body = null;
            //var response = instance.ApproveOrder(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AssignShipment
        /// </summary>
        [Fact]
        public void AssignShipmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderAssignShipmentRequest body = null;
            //var response = instance.AssignShipment(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CalculateRefund
        /// </summary>
        [Fact]
        public void CalculateRefundTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCalculateRefundRequest body = null;
            //var response = instance.CalculateRefund(body);
            //Assert.IsType<OrderCalculateRefundResponse>(response);
        }

        /// <summary>
        /// Test CancelFulfillment
        /// </summary>
        [Fact]
        public void CancelFulfillmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCancelFulfillmentRequest body = null;
            //var response = instance.CancelFulfillment(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CancelOrder
        /// </summary>
        [Fact]
        public void CancelOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCancelOrderRequest body = null;
            //var response = instance.CancelOrder(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CancelShipment
        /// </summary>
        [Fact]
        public void CancelShipmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCancelShipmentRequest body = null;
            //var response = instance.CancelShipment(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CompleteShipmentPacking
        /// </summary>
        [Fact]
        public void CompleteShipmentPackingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCompleteShipmentPackingRequest body = null;
            //var response = instance.CompleteShipmentPacking(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CreateFulfillment
        /// </summary>
        [Fact]
        public void CreateFulfillmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCreateFulfillmentRequest body = null;
            //var response = instance.CreateFulfillment(body);
            //Assert.IsType<OrderFulfillment>(response);
        }

        /// <summary>
        /// Test CreateOrder
        /// </summary>
        [Fact]
        public void CreateOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCreateOrderRequest body = null;
            //var response = instance.CreateOrder(body);
            //Assert.IsType<OrderOrderData>(response);
        }

        /// <summary>
        /// Test CreateOrderHistory
        /// </summary>
        [Fact]
        public void CreateOrderHistoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCreateHistoryRequest body = null;
            //var response = instance.CreateOrderHistory(body);
            //Assert.IsType<OrderDataHistory>(response);
        }

        /// <summary>
        /// Test CreatePayment
        /// </summary>
        [Fact]
        public void CreatePaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCreatePaymentRequest body = null;
            //var response = instance.CreatePayment(body);
            //Assert.IsType<OrderPayment>(response);
        }

        /// <summary>
        /// Test CreatePaymentTransaction
        /// </summary>
        [Fact]
        public void CreatePaymentTransactionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCreatePaymentTransactionRequest body = null;
            //var response = instance.CreatePaymentTransaction(body);
            //Assert.IsType<OrderTransaction>(response);
        }

        /// <summary>
        /// Test CreateRefund
        /// </summary>
        [Fact]
        public void CreateRefundTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCreateRefundRequest body = null;
            //var response = instance.CreateRefund(body);
            //Assert.IsType<OrderRefund>(response);
        }

        /// <summary>
        /// Test CreateRefundTransaction
        /// </summary>
        [Fact]
        public void CreateRefundTransactionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCreateRefundTransactionRequest body = null;
            //var response = instance.CreateRefundTransaction(body);
            //Assert.IsType<OrderTransaction>(response);
        }

        /// <summary>
        /// Test CreateShipment
        /// </summary>
        [Fact]
        public void CreateShipmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCreateShipmentRequest body = null;
            //var response = instance.CreateShipment(body);
            //Assert.IsType<OrderShipment>(response);
        }

        /// <summary>
        /// Test DeleteOrder
        /// </summary>
        [Fact]
        public void DeleteOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderDeleteOrderRequest body = null;
            //var response = instance.DeleteOrder(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GetFulfillment
        /// </summary>
        [Fact]
        public void GetFulfillmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderGetFulfillmentRequest body = null;
            //var response = instance.GetFulfillment(body);
            //Assert.IsType<OrderFulfillment>(response);
        }

        /// <summary>
        /// Test GetOrder
        /// </summary>
        [Fact]
        public void GetOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderGetOrderRequest body = null;
            //var response = instance.GetOrder(body);
            //Assert.IsType<OrderOrderData>(response);
        }

        /// <summary>
        /// Test GetOrderByCartId
        /// </summary>
        [Fact]
        public void GetOrderByCartIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderGetOrderByCartIdRequest body = null;
            //var response = instance.GetOrderByCartId(body);
            //Assert.IsType<OrderOrderData>(response);
        }

        /// <summary>
        /// Test GetOrderByOrderNumber
        /// </summary>
        [Fact]
        public void GetOrderByOrderNumberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderGetOrderByOrderNumberRequest body = null;
            //var response = instance.GetOrderByOrderNumber(body);
            //Assert.IsType<OrderOrderData>(response);
        }

        /// <summary>
        /// Test GetPayment
        /// </summary>
        [Fact]
        public void GetPaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderGetPaymentRequest body = null;
            //var response = instance.GetPayment(body);
            //Assert.IsType<OrderPayment>(response);
        }

        /// <summary>
        /// Test GetShipment
        /// </summary>
        [Fact]
        public void GetShipmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderGetShipmentRequest body = null;
            //var response = instance.GetShipment(body);
            //Assert.IsType<OrderShipment>(response);
        }

        /// <summary>
        /// Test GetTransaction
        /// </summary>
        [Fact]
        public void GetTransactionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderGetTransactionRequest body = null;
            //var response = instance.GetTransaction(body);
            //Assert.IsType<OrderTransaction>(response);
        }

        /// <summary>
        /// Test HoldOrder
        /// </summary>
        [Fact]
        public void HoldOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderHoldOrderRequest body = null;
            //var response = instance.HoldOrder(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ImportOrder
        /// </summary>
        [Fact]
        public void ImportOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderImportOrderRequest body = null;
            //var response = instance.ImportOrder(body);
            //Assert.IsType<OrderOrderData>(response);
        }

        /// <summary>
        /// Test ListFulfillments
        /// </summary>
        [Fact]
        public void ListFulfillmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderListFulfillmentsRequest body = null;
            //var response = instance.ListFulfillments(body);
            //Assert.IsType<OrderListFulfillmentsResponse>(response);
        }

        /// <summary>
        /// Test ListOrders
        /// </summary>
        [Fact]
        public void ListOrdersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderListOrdersRequest body = null;
            //var response = instance.ListOrders(body);
            //Assert.IsType<OrderListOrdersResponse>(response);
        }

        /// <summary>
        /// Test ListOrdersByCustomer
        /// </summary>
        [Fact]
        public void ListOrdersByCustomerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderListOrdersByCustomerRequest body = null;
            //var response = instance.ListOrdersByCustomer(body);
            //Assert.IsType<OrderListOrdersByCustomerResponse>(response);
        }

        /// <summary>
        /// Test ListOrdersByNumbers
        /// </summary>
        [Fact]
        public void ListOrdersByNumbersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderListOrdersByNumbersRequest body = null;
            //var response = instance.ListOrdersByNumbers(body);
            //Assert.IsType<OrderListOrdersByNumbersResponse>(response);
        }

        /// <summary>
        /// Test ListShipments
        /// </summary>
        [Fact]
        public void ListShipmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderListShipmentsRequest body = null;
            //var response = instance.ListShipments(body);
            //Assert.IsType<OrderListShipmentsResponse>(response);
        }

        /// <summary>
        /// Test PrintOrdersLabels
        /// </summary>
        [Fact]
        public void PrintOrdersLabelsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderPrintOrdersLabelsRequest body = null;
            //var response = instance.PrintOrdersLabels(body);
            //Assert.IsType<OrderPrintOrdersLabelsResponse>(response);
        }

        /// <summary>
        /// Test QuashFulfillment
        /// </summary>
        [Fact]
        public void QuashFulfillmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderQuashFulfillmentRequest body = null;
            //var response = instance.QuashFulfillment(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test QuashShipment
        /// </summary>
        [Fact]
        public void QuashShipmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderQuashShipmentRequest body = null;
            //var response = instance.QuashShipment(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ReceiveFulfillment
        /// </summary>
        [Fact]
        public void ReceiveFulfillmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderReceiveFulfillmentRequest body = null;
            //var response = instance.ReceiveFulfillment(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ReportFulfillmentError
        /// </summary>
        [Fact]
        public void ReportFulfillmentErrorTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderReportFulfillmentErrorRequest body = null;
            //var response = instance.ReportFulfillmentError(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ReportFulfillmentNotResolvable
        /// </summary>
        [Fact]
        public void ReportFulfillmentNotResolvableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderReportFulfillmentNotResolvableRequest body = null;
            //var response = instance.ReportFulfillmentNotResolvable(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ReportFulfillmentReady
        /// </summary>
        [Fact]
        public void ReportFulfillmentReadyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderReportFulfillmentReadyRequest body = null;
            //var response = instance.ReportFulfillmentReady(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ReportShipmentDelivery
        /// </summary>
        [Fact]
        public void ReportShipmentDeliveryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderReportShipmentDeliveryRequest body = null;
            //var response = instance.ReportShipmentDelivery(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ReportShipmentMissingStock
        /// </summary>
        [Fact]
        public void ReportShipmentMissingStockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderReportShipmentMissingStockRequest body = null;
            //var response = instance.ReportShipmentMissingStock(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ResolveShipmentMissingStock
        /// </summary>
        [Fact]
        public void ResolveShipmentMissingStockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderResolveShipmentMissingStockRequest body = null;
            //var response = instance.ResolveShipmentMissingStock(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test RetryFulfillment
        /// </summary>
        [Fact]
        public void RetryFulfillmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderRetryFulfillmentRequest body = null;
            //var response = instance.RetryFulfillment(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test SearchOrders
        /// </summary>
        [Fact]
        public void SearchOrdersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderSearchOrdersRequest body = null;
            //var response = instance.SearchOrders(body);
            //Assert.IsType<OrderSearchOrdersResponse>(response);
        }

        /// <summary>
        /// Test SendFulfillment
        /// </summary>
        [Fact]
        public void SendFulfillmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderSendFulfillmentRequest body = null;
            //var response = instance.SendFulfillment(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test SendOrderNotification
        /// </summary>
        [Fact]
        public void SendOrderNotificationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderSendOrderNotificationRequest body = null;
            //var response = instance.SendOrderNotification(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test StartFulfillmentProcessing
        /// </summary>
        [Fact]
        public void StartFulfillmentProcessingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderStartFulfillmentProcessingRequest body = null;
            //var response = instance.StartFulfillmentProcessing(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test StartShipmentProcessing
        /// </summary>
        [Fact]
        public void StartShipmentProcessingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderStartShipmentProcessingRequest body = null;
            //var response = instance.StartShipmentProcessing(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test UnholdOrder
        /// </summary>
        [Fact]
        public void UnholdOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderUnholdOrderRequest body = null;
            //var response = instance.UnholdOrder(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test UpdateOrder
        /// </summary>
        [Fact]
        public void UpdateOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderUpdateOrderRequest body = null;
            //var response = instance.UpdateOrder(body);
            //Assert.IsType<OrderOrderData>(response);
        }

        /// <summary>
        /// Test UpdatePayment
        /// </summary>
        [Fact]
        public void UpdatePaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderUpdatePaymentRequest body = null;
            //var response = instance.UpdatePayment(body);
            //Assert.IsType<OrderPayment>(response);
        }
    }
}
