/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing ImportOrderRequestImportedPayment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImportOrderRequestImportedPaymentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImportOrderRequestImportedPayment
        //private ImportOrderRequestImportedPayment instance;

        public ImportOrderRequestImportedPaymentTests()
        {
            // TODO uncomment below to create an instance of ImportOrderRequestImportedPayment
            //instance = new ImportOrderRequestImportedPayment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImportOrderRequestImportedPayment
        /// </summary>
        [Fact]
        public void ImportOrderRequestImportedPaymentInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImportOrderRequestImportedPayment
            //Assert.IsType<ImportOrderRequestImportedPayment>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }

        /// <summary>
        /// Test the property 'Amounts'
        /// </summary>
        [Fact]
        public void AmountsTest()
        {
            // TODO unit test for the property 'Amounts'
        }

        /// <summary>
        /// Test the property 'CcInfo'
        /// </summary>
        [Fact]
        public void CcInfoTest()
        {
            // TODO unit test for the property 'CcInfo'
        }

        /// <summary>
        /// Test the property 'IsUpfront'
        /// </summary>
        [Fact]
        public void IsUpfrontTest()
        {
            // TODO unit test for the property 'IsUpfront'
        }
    }
}
