/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreatePaymentTransactionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreatePaymentTransactionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreatePaymentTransactionRequest
        //private OrderCreatePaymentTransactionRequest instance;

        public OrderCreatePaymentTransactionRequestTests()
        {
            // TODO uncomment below to create an instance of OrderCreatePaymentTransactionRequest
            //instance = new OrderCreatePaymentTransactionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreatePaymentTransactionRequest
        /// </summary>
        [Fact]
        public void OrderCreatePaymentTransactionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreatePaymentTransactionRequest
            //Assert.IsType<OrderCreatePaymentTransactionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }
    }
}
