/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderListFulfillmentsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderListFulfillmentsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderListFulfillmentsResponse
        //private OrderListFulfillmentsResponse instance;

        public OrderListFulfillmentsResponseTests()
        {
            // TODO uncomment below to create an instance of OrderListFulfillmentsResponse
            //instance = new OrderListFulfillmentsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderListFulfillmentsResponse
        /// </summary>
        [Fact]
        public void OrderListFulfillmentsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderListFulfillmentsResponse
            //Assert.IsType<OrderListFulfillmentsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Fulfillments'
        /// </summary>
        [Fact]
        public void FulfillmentsTest()
        {
            // TODO unit test for the property 'Fulfillments'
        }
    }
}
