/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateOrderRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateOrderRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateOrderRequest
        //private OrderCreateOrderRequest instance;

        public OrderCreateOrderRequestTests()
        {
            // TODO uncomment below to create an instance of OrderCreateOrderRequest
            //instance = new OrderCreateOrderRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateOrderRequest
        /// </summary>
        [Fact]
        public void OrderCreateOrderRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateOrderRequest
            //Assert.IsType<OrderCreateOrderRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }

        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Fact]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }

        /// <summary>
        /// Test the property 'Market'
        /// </summary>
        [Fact]
        public void MarketTest()
        {
            // TODO unit test for the property 'Market'
        }

        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'PaymentsInfo'
        /// </summary>
        [Fact]
        public void PaymentsInfoTest()
        {
            // TODO unit test for the property 'PaymentsInfo'
        }

        /// <summary>
        /// Test the property 'ShipmentsInfo'
        /// </summary>
        [Fact]
        public void ShipmentsInfoTest()
        {
            // TODO unit test for the property 'ShipmentsInfo'
        }

        /// <summary>
        /// Test the property 'Promotions'
        /// </summary>
        [Fact]
        public void PromotionsTest()
        {
            // TODO unit test for the property 'Promotions'
        }

        /// <summary>
        /// Test the property 'Payments'
        /// </summary>
        [Fact]
        public void PaymentsTest()
        {
            // TODO unit test for the property 'Payments'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Subtotals'
        /// </summary>
        [Fact]
        public void SubtotalsTest()
        {
            // TODO unit test for the property 'Subtotals'
        }

        /// <summary>
        /// Test the property 'Totals'
        /// </summary>
        [Fact]
        public void TotalsTest()
        {
            // TODO unit test for the property 'Totals'
        }

        /// <summary>
        /// Test the property 'VatIncluded'
        /// </summary>
        [Fact]
        public void VatIncludedTest()
        {
            // TODO unit test for the property 'VatIncluded'
        }

        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Fact]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }

        /// <summary>
        /// Test the property 'ShippingAddress'
        /// </summary>
        [Fact]
        public void ShippingAddressTest()
        {
            // TODO unit test for the property 'ShippingAddress'
        }

        /// <summary>
        /// Test the property 'CustomerInfo'
        /// </summary>
        [Fact]
        public void CustomerInfoTest()
        {
            // TODO unit test for the property 'CustomerInfo'
        }

        /// <summary>
        /// Test the property 'CartGrn'
        /// </summary>
        [Fact]
        public void CartGrnTest()
        {
            // TODO unit test for the property 'CartGrn'
        }

        /// <summary>
        /// Test the property 'OnHold'
        /// </summary>
        [Fact]
        public void OnHoldTest()
        {
            // TODO unit test for the property 'OnHold'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
    }
}
