/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDataCustomerInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDataCustomerInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDataCustomerInfo
        //private OrderDataCustomerInfo instance;

        public OrderDataCustomerInfoTests()
        {
            // TODO uncomment below to create an instance of OrderDataCustomerInfo
            //instance = new OrderDataCustomerInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDataCustomerInfo
        /// </summary>
        [Fact]
        public void OrderDataCustomerInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDataCustomerInfo
            //Assert.IsType<OrderDataCustomerInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Fact]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }

        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Fact]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Segment'
        /// </summary>
        [Fact]
        public void SegmentTest()
        {
            // TODO unit test for the property 'Segment'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'CertifiedEmail'
        /// </summary>
        [Fact]
        public void CertifiedEmailTest()
        {
            // TODO unit test for the property 'CertifiedEmail'
        }

        /// <summary>
        /// Test the property 'TaxCode'
        /// </summary>
        [Fact]
        public void TaxCodeTest()
        {
            // TODO unit test for the property 'TaxCode'
        }
    }
}
