/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDataDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDataDocumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDataDocument
        //private OrderDataDocument instance;

        public OrderDataDocumentTests()
        {
            // TODO uncomment below to create an instance of OrderDataDocument
            //instance = new OrderDataDocument();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDataDocument
        /// </summary>
        [Fact]
        public void OrderDataDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDataDocument
            //Assert.IsType<OrderDataDocument>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'AssetGrn'
        /// </summary>
        [Fact]
        public void AssetGrnTest()
        {
            // TODO unit test for the property 'AssetGrn'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'InsertedAt'
        /// </summary>
        [Fact]
        public void InsertedAtTest()
        {
            // TODO unit test for the property 'InsertedAt'
        }
    }
}
