/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderPrintOrdersLabelsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderPrintOrdersLabelsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderPrintOrdersLabelsResponse
        //private OrderPrintOrdersLabelsResponse instance;

        public OrderPrintOrdersLabelsResponseTests()
        {
            // TODO uncomment below to create an instance of OrderPrintOrdersLabelsResponse
            //instance = new OrderPrintOrdersLabelsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderPrintOrdersLabelsResponse
        /// </summary>
        [Fact]
        public void OrderPrintOrdersLabelsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderPrintOrdersLabelsResponse
            //Assert.IsType<OrderPrintOrdersLabelsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'DownloadUrl'
        /// </summary>
        [Fact]
        public void DownloadUrlTest()
        {
            // TODO unit test for the property 'DownloadUrl'
        }

        /// <summary>
        /// Test the property 'FailedOrders'
        /// </summary>
        [Fact]
        public void FailedOrdersTest()
        {
            // TODO unit test for the property 'FailedOrders'
        }
    }
}
