/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderListFulfillmentsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderListFulfillmentsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderListFulfillmentsRequest
        //private OrderListFulfillmentsRequest instance;

        public OrderListFulfillmentsRequestTests()
        {
            // TODO uncomment below to create an instance of OrderListFulfillmentsRequest
            //instance = new OrderListFulfillmentsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderListFulfillmentsRequest
        /// </summary>
        [Fact]
        public void OrderListFulfillmentsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderListFulfillmentsRequest
            //Assert.IsType<OrderListFulfillmentsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
    }
}
