/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderStatusFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderStatusFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderStatusFilter
        //private OrderStatusFilter instance;

        public OrderStatusFilterTests()
        {
            // TODO uncomment below to create an instance of OrderStatusFilter
            //instance = new OrderStatusFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderStatusFilter
        /// </summary>
        [Fact]
        public void OrderStatusFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderStatusFilter
            //Assert.IsType<OrderStatusFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Statuses'
        /// </summary>
        [Fact]
        public void StatusesTest()
        {
            // TODO unit test for the property 'Statuses'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
    }
}
