/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCalculateRefundResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCalculateRefundResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCalculateRefundResponse
        //private OrderCalculateRefundResponse instance;

        public OrderCalculateRefundResponseTests()
        {
            // TODO uncomment below to create an instance of OrderCalculateRefundResponse
            //instance = new OrderCalculateRefundResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCalculateRefundResponse
        /// </summary>
        [Fact]
        public void OrderCalculateRefundResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCalculateRefundResponse
            //Assert.IsType<OrderCalculateRefundResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CreateRefundRequest'
        /// </summary>
        [Fact]
        public void CreateRefundRequestTest()
        {
            // TODO unit test for the property 'CreateRefundRequest'
        }
    }
}
