/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderMoney
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderMoneyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderMoney
        //private OrderMoney instance;

        public OrderMoneyTests()
        {
            // TODO uncomment below to create an instance of OrderMoney
            //instance = new OrderMoney();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderMoney
        /// </summary>
        [Fact]
        public void OrderMoneyInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderMoney
            //Assert.IsType<OrderMoney>(instance);
        }

        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Fact]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }

        /// <summary>
        /// Test the property 'Micros'
        /// </summary>
        [Fact]
        public void MicrosTest()
        {
            // TODO unit test for the property 'Micros'
        }
    }
}
