/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateRefundTransactionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateRefundTransactionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateRefundTransactionRequest
        //private OrderCreateRefundTransactionRequest instance;

        public OrderCreateRefundTransactionRequestTests()
        {
            // TODO uncomment below to create an instance of OrderCreateRefundTransactionRequest
            //instance = new OrderCreateRefundTransactionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateRefundTransactionRequest
        /// </summary>
        [Fact]
        public void OrderCreateRefundTransactionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateRefundTransactionRequest
            //Assert.IsType<OrderCreateRefundTransactionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'RefundId'
        /// </summary>
        [Fact]
        public void RefundIdTest()
        {
            // TODO unit test for the property 'RefundId'
        }

        /// <summary>
        /// Test the property 'ParentTransactionId'
        /// </summary>
        [Fact]
        public void ParentTransactionIdTest()
        {
            // TODO unit test for the property 'ParentTransactionId'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }
    }
}
