/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderReportShipmentDeliveryRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderReportShipmentDeliveryRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderReportShipmentDeliveryRequest
        //private OrderReportShipmentDeliveryRequest instance;

        public OrderReportShipmentDeliveryRequestTests()
        {
            // TODO uncomment below to create an instance of OrderReportShipmentDeliveryRequest
            //instance = new OrderReportShipmentDeliveryRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderReportShipmentDeliveryRequest
        /// </summary>
        [Fact]
        public void OrderReportShipmentDeliveryRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderReportShipmentDeliveryRequest
            //Assert.IsType<OrderReportShipmentDeliveryRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ShipmentId'
        /// </summary>
        [Fact]
        public void ShipmentIdTest()
        {
            // TODO unit test for the property 'ShipmentId'
        }
    }
}
