/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateRefundRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateRefundRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateRefundRequest
        //private OrderCreateRefundRequest instance;

        public OrderCreateRefundRequestTests()
        {
            // TODO uncomment below to create an instance of OrderCreateRefundRequest
            //instance = new OrderCreateRefundRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateRefundRequest
        /// </summary>
        [Fact]
        public void OrderCreateRefundRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateRefundRequest
            //Assert.IsType<OrderCreateRefundRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'Amounts'
        /// </summary>
        [Fact]
        public void AmountsTest()
        {
            // TODO unit test for the property 'Amounts'
        }

        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }

        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }
    }
}
