/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDataShipmentInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDataShipmentInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDataShipmentInfo
        //private OrderDataShipmentInfo instance;

        public OrderDataShipmentInfoTests()
        {
            // TODO uncomment below to create an instance of OrderDataShipmentInfo
            //instance = new OrderDataShipmentInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDataShipmentInfo
        /// </summary>
        [Fact]
        public void OrderDataShipmentInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDataShipmentInfo
            //Assert.IsType<OrderDataShipmentInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }

        /// <summary>
        /// Test the property 'VatAmount'
        /// </summary>
        [Fact]
        public void VatAmountTest()
        {
            // TODO unit test for the property 'VatAmount'
        }

        /// <summary>
        /// Test the property 'VatPercentage'
        /// </summary>
        [Fact]
        public void VatPercentageTest()
        {
            // TODO unit test for the property 'VatPercentage'
        }

        /// <summary>
        /// Test the property 'VatInaccurate'
        /// </summary>
        [Fact]
        public void VatInaccurateTest()
        {
            // TODO unit test for the property 'VatInaccurate'
        }

        /// <summary>
        /// Test the property 'VatCalculated'
        /// </summary>
        [Fact]
        public void VatCalculatedTest()
        {
            // TODO unit test for the property 'VatCalculated'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'FromAddress'
        /// </summary>
        [Fact]
        public void FromAddressTest()
        {
            // TODO unit test for the property 'FromAddress'
        }

        /// <summary>
        /// Test the property 'ReturnAddress'
        /// </summary>
        [Fact]
        public void ReturnAddressTest()
        {
            // TODO unit test for the property 'ReturnAddress'
        }
    }
}
