/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderTransactionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderTransactionTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderTransactionType
        //private OrderTransactionType instance;

        public OrderTransactionTypeTests()
        {
            // TODO uncomment below to create an instance of OrderTransactionType
            //instance = new OrderTransactionType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderTransactionType
        /// </summary>
        [Fact]
        public void OrderTransactionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderTransactionType
            //Assert.IsType<OrderTransactionType>(instance);
        }
    }
}
