/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderPaymentFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderPaymentFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderPaymentFilter
        //private OrderPaymentFilter instance;

        public OrderPaymentFilterTests()
        {
            // TODO uncomment below to create an instance of OrderPaymentFilter
            //instance = new OrderPaymentFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderPaymentFilter
        /// </summary>
        [Fact]
        public void OrderPaymentFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderPaymentFilter
            //Assert.IsType<OrderPaymentFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Codes'
        /// </summary>
        [Fact]
        public void CodesTest()
        {
            // TODO unit test for the property 'Codes'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
    }
}
