/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing OrderRefundItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderRefundItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderRefundItem
        //private OrderRefundItem instance;

        public OrderRefundItemTests()
        {
            // TODO uncomment below to create an instance of OrderRefundItem
            //instance = new OrderRefundItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderRefundItem
        /// </summary>
        [Fact]
        public void OrderRefundItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderRefundItem
            //Assert.IsType<OrderRefundItem>(instance);
        }

        /// <summary>
        /// Test the property 'OrderItemId'
        /// </summary>
        [Fact]
        public void OrderItemIdTest()
        {
            // TODO unit test for the property 'OrderItemId'
        }

        /// <summary>
        /// Test the property 'Qty'
        /// </summary>
        [Fact]
        public void QtyTest()
        {
            // TODO unit test for the property 'Qty'
        }
    }
}
