/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentCcInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentCcInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentCcInfo
        //private PaymentCcInfo instance;

        public PaymentCcInfoTests()
        {
            // TODO uncomment below to create an instance of PaymentCcInfo
            //instance = new PaymentCcInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentCcInfo
        /// </summary>
        [Fact]
        public void PaymentCcInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentCcInfo
            //Assert.IsType<PaymentCcInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Approval'
        /// </summary>
        [Fact]
        public void ApprovalTest()
        {
            // TODO unit test for the property 'Approval'
        }

        /// <summary>
        /// Test the property 'ExpMonth'
        /// </summary>
        [Fact]
        public void ExpMonthTest()
        {
            // TODO unit test for the property 'ExpMonth'
        }

        /// <summary>
        /// Test the property 'ExpYear'
        /// </summary>
        [Fact]
        public void ExpYearTest()
        {
            // TODO unit test for the property 'ExpYear'
        }

        /// <summary>
        /// Test the property 'Last4'
        /// </summary>
        [Fact]
        public void Last4Test()
        {
            // TODO unit test for the property 'Last4'
        }

        /// <summary>
        /// Test the property 'NumberEnc'
        /// </summary>
        [Fact]
        public void NumberEncTest()
        {
            // TODO unit test for the property 'NumberEnc'
        }

        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }

        /// <summary>
        /// Test the property 'AvsStatus'
        /// </summary>
        [Fact]
        public void AvsStatusTest()
        {
            // TODO unit test for the property 'AvsStatus'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
