/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using order.Model;
using order.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace order.Test.Model
{
    /// <summary>
    ///  Class for testing ProductConfigurationStepOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductConfigurationStepOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductConfigurationStepOption
        //private ProductConfigurationStepOption instance;

        public ProductConfigurationStepOptionTests()
        {
            // TODO uncomment below to create an instance of ProductConfigurationStepOption
            //instance = new ProductConfigurationStepOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductConfigurationStepOption
        /// </summary>
        [Fact]
        public void ProductConfigurationStepOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductConfigurationStepOption
            //Assert.IsType<ProductConfigurationStepOption>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'PriceVariation'
        /// </summary>
        [Fact]
        public void PriceVariationTest()
        {
            // TODO unit test for the property 'PriceVariation'
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

        /// <summary>
        /// Test the property 'HasQuantity'
        /// </summary>
        [Fact]
        public void HasQuantityTest()
        {
            // TODO unit test for the property 'HasQuantity'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
    }
}
