/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = order.Client.OpenAPIDateConverter;

namespace order.Model
{
    /// <summary>
    /// ImportOrderRequestImportedPayment
    /// </summary>
    [DataContract(Name = "ImportOrderRequestImportedPayment")]
    public partial class ImportOrderRequestImportedPayment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImportOrderRequestImportedPayment" /> class.
        /// </summary>
        /// <param name="code">code.</param>
        /// <param name="additionalInfo">additionalInfo.</param>
        /// <param name="amounts">amounts.</param>
        /// <param name="ccInfo">ccInfo.</param>
        public ImportOrderRequestImportedPayment(string code = default(string), string additionalInfo = default(string), List<OrderPaymentAmount> amounts = default(List<OrderPaymentAmount>), PaymentCcInfo ccInfo = default(PaymentCcInfo))
        {
            this.Code = code;
            this.AdditionalInfo = additionalInfo;
            this.Amounts = amounts;
            this.CcInfo = ccInfo;
        }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalInfo
        /// </summary>
        [DataMember(Name = "additionalInfo", EmitDefaultValue = false)]
        public string AdditionalInfo { get; set; }

        /// <summary>
        /// Gets or Sets Amounts
        /// </summary>
        [DataMember(Name = "amounts", EmitDefaultValue = false)]
        public List<OrderPaymentAmount> Amounts { get; set; }

        /// <summary>
        /// Gets or Sets CcInfo
        /// </summary>
        [DataMember(Name = "ccInfo", EmitDefaultValue = false)]
        public PaymentCcInfo CcInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImportOrderRequestImportedPayment {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  AdditionalInfo: ").Append(AdditionalInfo).Append("\n");
            sb.Append("  Amounts: ").Append(Amounts).Append("\n");
            sb.Append("  CcInfo: ").Append(CcInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
