/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = order.Client.OpenAPIDateConverter;

namespace order.Model
{
    /// <summary>
    /// OrderPrintOrdersLabelsResponse
    /// </summary>
    [DataContract(Name = "orderPrintOrdersLabelsResponse")]
    public partial class OrderPrintOrdersLabelsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderPrintOrdersLabelsResponse" /> class.
        /// </summary>
        /// <param name="downloadUrl">downloadUrl.</param>
        /// <param name="failedOrders">failedOrders.</param>
        public OrderPrintOrdersLabelsResponse(string downloadUrl = default(string), List<PrintOrdersLabelsResponseFailedOrder> failedOrders = default(List<PrintOrdersLabelsResponseFailedOrder>))
        {
            this.DownloadUrl = downloadUrl;
            this.FailedOrders = failedOrders;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets DownloadUrl
        /// </summary>
        [DataMember(Name = "downloadUrl", EmitDefaultValue = false)]
        public string DownloadUrl { get; set; }

        /// <summary>
        /// Gets or Sets FailedOrders
        /// </summary>
        [DataMember(Name = "failedOrders", EmitDefaultValue = false)]
        public List<PrintOrdersLabelsResponseFailedOrder> FailedOrders { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderPrintOrdersLabelsResponse {\n");
            sb.Append("  DownloadUrl: ").Append(DownloadUrl).Append("\n");
            sb.Append("  FailedOrders: ").Append(FailedOrders).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
