/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = order.Client.OpenAPIDateConverter;

namespace order.Model
{
    /// <summary>
    /// OrderCreateOrderRequest
    /// </summary>
    [DataContract(Name = "orderCreateOrderRequest")]
    public partial class OrderCreateOrderRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", EmitDefaultValue = false)]
        public OrderCurrency? Currency { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCreateOrderRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId.</param>
        /// <param name="number">number.</param>
        /// <param name="channel">channel.</param>
        /// <param name="market">market.</param>
        /// <param name="locale">locale.</param>
        /// <param name="items">items.</param>
        /// <param name="paymentsInfo">paymentsInfo.</param>
        /// <param name="shipmentsInfo">shipmentsInfo.</param>
        /// <param name="promotions">promotions.</param>
        /// <param name="payments">payments.</param>
        /// <param name="currency">currency.</param>
        /// <param name="subtotals">subtotals.</param>
        /// <param name="totals">totals.</param>
        /// <param name="vatIncluded">vatIncluded.</param>
        /// <param name="billingAddress">billingAddress.</param>
        /// <param name="shippingAddress">shippingAddress.</param>
        /// <param name="customerInfo">customerInfo.</param>
        /// <param name="cartGrn">cartGrn.</param>
        /// <param name="onHold">onHold.</param>
        /// <param name="notes">notes.</param>
        public OrderCreateOrderRequest(string tenantId = default(string), string number = default(string), string channel = default(string), string market = default(string), string locale = default(string), List<OrderOrderDataItem> items = default(List<OrderOrderDataItem>), List<OrderDataPaymentInfo> paymentsInfo = default(List<OrderDataPaymentInfo>), List<OrderDataShipmentInfo> shipmentsInfo = default(List<OrderDataShipmentInfo>), List<OrderDataPromotionInfo> promotions = default(List<OrderDataPromotionInfo>), List<CreateOrderRequestInitialPayment> payments = default(List<CreateOrderRequestInitialPayment>), OrderCurrency? currency = default(OrderCurrency?), Dictionary<string, OrderDataSubtotal> subtotals = default(Dictionary<string, OrderDataSubtotal>), Dictionary<string, OrderDataTotal> totals = default(Dictionary<string, OrderDataTotal>), bool vatIncluded = default(bool), OrderPostalAddress billingAddress = default(OrderPostalAddress), OrderPostalAddress shippingAddress = default(OrderPostalAddress), OrderDataCustomerInfo customerInfo = default(OrderDataCustomerInfo), string cartGrn = default(string), bool onHold = default(bool), string notes = default(string))
        {
            this.TenantId = tenantId;
            this.Number = number;
            this.Channel = channel;
            this.Market = market;
            this.Locale = locale;
            this.Items = items;
            this.PaymentsInfo = paymentsInfo;
            this.ShipmentsInfo = shipmentsInfo;
            this.Promotions = promotions;
            this.Payments = payments;
            this.Currency = currency;
            this.Subtotals = subtotals;
            this.Totals = totals;
            this.VatIncluded = vatIncluded;
            this.BillingAddress = billingAddress;
            this.ShippingAddress = shippingAddress;
            this.CustomerInfo = customerInfo;
            this.CartGrn = cartGrn;
            this.OnHold = onHold;
            this.Notes = notes;
        }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [DataMember(Name = "tenantId", EmitDefaultValue = false)]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [DataMember(Name = "number", EmitDefaultValue = false)]
        public string Number { get; set; }

        /// <summary>
        /// Gets or Sets Channel
        /// </summary>
        [DataMember(Name = "channel", EmitDefaultValue = false)]
        public string Channel { get; set; }

        /// <summary>
        /// Gets or Sets Market
        /// </summary>
        [DataMember(Name = "market", EmitDefaultValue = false)]
        public string Market { get; set; }

        /// <summary>
        /// Gets or Sets Locale
        /// </summary>
        [DataMember(Name = "locale", EmitDefaultValue = false)]
        public string Locale { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name = "items", EmitDefaultValue = false)]
        public List<OrderOrderDataItem> Items { get; set; }

        /// <summary>
        /// Gets or Sets PaymentsInfo
        /// </summary>
        [DataMember(Name = "paymentsInfo", EmitDefaultValue = false)]
        public List<OrderDataPaymentInfo> PaymentsInfo { get; set; }

        /// <summary>
        /// Gets or Sets ShipmentsInfo
        /// </summary>
        [DataMember(Name = "shipmentsInfo", EmitDefaultValue = false)]
        public List<OrderDataShipmentInfo> ShipmentsInfo { get; set; }

        /// <summary>
        /// Gets or Sets Promotions
        /// </summary>
        [DataMember(Name = "promotions", EmitDefaultValue = false)]
        public List<OrderDataPromotionInfo> Promotions { get; set; }

        /// <summary>
        /// Gets or Sets Payments
        /// </summary>
        [DataMember(Name = "payments", EmitDefaultValue = false)]
        public List<CreateOrderRequestInitialPayment> Payments { get; set; }

        /// <summary>
        /// Gets or Sets Subtotals
        /// </summary>
        [DataMember(Name = "subtotals", EmitDefaultValue = false)]
        public Dictionary<string, OrderDataSubtotal> Subtotals { get; set; }

        /// <summary>
        /// Gets or Sets Totals
        /// </summary>
        [DataMember(Name = "totals", EmitDefaultValue = false)]
        public Dictionary<string, OrderDataTotal> Totals { get; set; }

        /// <summary>
        /// Gets or Sets VatIncluded
        /// </summary>
        [DataMember(Name = "vatIncluded", EmitDefaultValue = true)]
        public bool VatIncluded { get; set; }

        /// <summary>
        /// Gets or Sets BillingAddress
        /// </summary>
        [DataMember(Name = "billingAddress", EmitDefaultValue = false)]
        public OrderPostalAddress BillingAddress { get; set; }

        /// <summary>
        /// Gets or Sets ShippingAddress
        /// </summary>
        [DataMember(Name = "shippingAddress", EmitDefaultValue = false)]
        public OrderPostalAddress ShippingAddress { get; set; }

        /// <summary>
        /// Gets or Sets CustomerInfo
        /// </summary>
        [DataMember(Name = "customerInfo", EmitDefaultValue = false)]
        public OrderDataCustomerInfo CustomerInfo { get; set; }

        /// <summary>
        /// Gets or Sets CartGrn
        /// </summary>
        [DataMember(Name = "cartGrn", EmitDefaultValue = false)]
        public string CartGrn { get; set; }

        /// <summary>
        /// Gets or Sets OnHold
        /// </summary>
        [DataMember(Name = "onHold", EmitDefaultValue = true)]
        public bool OnHold { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [DataMember(Name = "notes", EmitDefaultValue = false)]
        public string Notes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderCreateOrderRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  Channel: ").Append(Channel).Append("\n");
            sb.Append("  Market: ").Append(Market).Append("\n");
            sb.Append("  Locale: ").Append(Locale).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  PaymentsInfo: ").Append(PaymentsInfo).Append("\n");
            sb.Append("  ShipmentsInfo: ").Append(ShipmentsInfo).Append("\n");
            sb.Append("  Promotions: ").Append(Promotions).Append("\n");
            sb.Append("  Payments: ").Append(Payments).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Subtotals: ").Append(Subtotals).Append("\n");
            sb.Append("  Totals: ").Append(Totals).Append("\n");
            sb.Append("  VatIncluded: ").Append(VatIncluded).Append("\n");
            sb.Append("  BillingAddress: ").Append(BillingAddress).Append("\n");
            sb.Append("  ShippingAddress: ").Append(ShippingAddress).Append("\n");
            sb.Append("  CustomerInfo: ").Append(CustomerInfo).Append("\n");
            sb.Append("  CartGrn: ").Append(CartGrn).Append("\n");
            sb.Append("  OnHold: ").Append(OnHold).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
