/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = order.Client.OpenAPIDateConverter;

namespace order.Model
{
    /// <summary>
    /// OrderCreateRefundTransactionRequest
    /// </summary>
    [DataContract(Name = "orderCreateRefundTransactionRequest")]
    public partial class OrderCreateRefundTransactionRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public OrderTransactionType? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCreateRefundTransactionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OrderCreateRefundTransactionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCreateRefundTransactionRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId (required).</param>
        /// <param name="refundId">refundId (required).</param>
        /// <param name="parentTransactionId">parentTransactionId.</param>
        /// <param name="type">type.</param>
        /// <param name="additionalInfo">additionalInfo.</param>
        public OrderCreateRefundTransactionRequest(string tenantId = default(string), string refundId = default(string), string parentTransactionId = default(string), OrderTransactionType? type = default(OrderTransactionType?), string additionalInfo = default(string))
        {
            // to ensure "tenantId" is required (not null)
            if (tenantId == null)
            {
                throw new ArgumentNullException("tenantId is a required property for OrderCreateRefundTransactionRequest and cannot be null");
            }
            this.TenantId = tenantId;
            // to ensure "refundId" is required (not null)
            if (refundId == null)
            {
                throw new ArgumentNullException("refundId is a required property for OrderCreateRefundTransactionRequest and cannot be null");
            }
            this.RefundId = refundId;
            this.ParentTransactionId = parentTransactionId;
            this.Type = type;
            this.AdditionalInfo = additionalInfo;
        }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [DataMember(Name = "tenantId", IsRequired = true, EmitDefaultValue = true)]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets RefundId
        /// </summary>
        [DataMember(Name = "refundId", IsRequired = true, EmitDefaultValue = true)]
        public string RefundId { get; set; }

        /// <summary>
        /// Gets or Sets ParentTransactionId
        /// </summary>
        [DataMember(Name = "parentTransactionId", EmitDefaultValue = false)]
        public string ParentTransactionId { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalInfo
        /// </summary>
        [DataMember(Name = "additionalInfo", EmitDefaultValue = false)]
        public string AdditionalInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderCreateRefundTransactionRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  RefundId: ").Append(RefundId).Append("\n");
            sb.Append("  ParentTransactionId: ").Append(ParentTransactionId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  AdditionalInfo: ").Append(AdditionalInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
