/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = order.Client.OpenAPIDateConverter;

namespace order.Model
{
    /// <summary>
    /// OrderSearchOrdersRequest
    /// </summary>
    [DataContract(Name = "orderSearchOrdersRequest")]
    public partial class OrderSearchOrdersRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderSearchOrdersRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OrderSearchOrdersRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderSearchOrdersRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId (required).</param>
        /// <param name="searchQuery">searchQuery.</param>
        /// <param name="pageSize">The maximum number of orders to return. The service may return fewer than this value. If unspecified, at most 10 orders will be returned. The maximum value is 100; values above 100 will be coerced to 100..</param>
        /// <param name="pageToken">A page token, received from a previous &#x60;ListOrders&#x60; call. Provide this to retrieve the subsequent page.   When paginating, all other parameters provided to &#x60;ListOrders&#x60; must match the call that provided the page token..</param>
        /// <param name="orderBy">orderBy.</param>
        /// <param name="statusFilter">statusFilter.</param>
        /// <param name="fromDate">fromDate.</param>
        /// <param name="toDate">toDate.</param>
        /// <param name="paymentFilter">paymentFilter.</param>
        /// <param name="agentGrn">agentGrn.</param>
        /// <param name="updatedFrom">updatedFrom.</param>
        /// <param name="updatedTo">updatedTo.</param>
        public OrderSearchOrdersRequest(string tenantId = default(string), string searchQuery = default(string), long pageSize = default(long), string pageToken = default(string), List<OrderOrderBy> orderBy = default(List<OrderOrderBy>), OrderStatusFilter statusFilter = default(OrderStatusFilter), DateTime fromDate = default(DateTime), DateTime toDate = default(DateTime), OrderPaymentFilter paymentFilter = default(OrderPaymentFilter), string agentGrn = default(string), DateTime updatedFrom = default(DateTime), DateTime updatedTo = default(DateTime))
        {
            // to ensure "tenantId" is required (not null)
            if (tenantId == null)
            {
                throw new ArgumentNullException("tenantId is a required property for OrderSearchOrdersRequest and cannot be null");
            }
            this.TenantId = tenantId;
            this.SearchQuery = searchQuery;
            this.PageSize = pageSize;
            this.PageToken = pageToken;
            this.OrderBy = orderBy;
            this.StatusFilter = statusFilter;
            this.FromDate = fromDate;
            this.ToDate = toDate;
            this.PaymentFilter = paymentFilter;
            this.AgentGrn = agentGrn;
            this.UpdatedFrom = updatedFrom;
            this.UpdatedTo = updatedTo;
        }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [DataMember(Name = "tenantId", IsRequired = true, EmitDefaultValue = true)]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets SearchQuery
        /// </summary>
        [DataMember(Name = "searchQuery", EmitDefaultValue = false)]
        public string SearchQuery { get; set; }

        /// <summary>
        /// The maximum number of orders to return. The service may return fewer than this value. If unspecified, at most 10 orders will be returned. The maximum value is 100; values above 100 will be coerced to 100.
        /// </summary>
        /// <value>The maximum number of orders to return. The service may return fewer than this value. If unspecified, at most 10 orders will be returned. The maximum value is 100; values above 100 will be coerced to 100.</value>
        [DataMember(Name = "pageSize", EmitDefaultValue = false)]
        public long PageSize { get; set; }

        /// <summary>
        /// A page token, received from a previous &#x60;ListOrders&#x60; call. Provide this to retrieve the subsequent page.   When paginating, all other parameters provided to &#x60;ListOrders&#x60; must match the call that provided the page token.
        /// </summary>
        /// <value>A page token, received from a previous &#x60;ListOrders&#x60; call. Provide this to retrieve the subsequent page.   When paginating, all other parameters provided to &#x60;ListOrders&#x60; must match the call that provided the page token.</value>
        [DataMember(Name = "pageToken", EmitDefaultValue = false)]
        public string PageToken { get; set; }

        /// <summary>
        /// Gets or Sets OrderBy
        /// </summary>
        [DataMember(Name = "orderBy", EmitDefaultValue = false)]
        public List<OrderOrderBy> OrderBy { get; set; }

        /// <summary>
        /// Gets or Sets StatusFilter
        /// </summary>
        [DataMember(Name = "statusFilter", EmitDefaultValue = false)]
        public OrderStatusFilter StatusFilter { get; set; }

        /// <summary>
        /// Gets or Sets FromDate
        /// </summary>
        [DataMember(Name = "fromDate", EmitDefaultValue = false)]
        public DateTime FromDate { get; set; }

        /// <summary>
        /// Gets or Sets ToDate
        /// </summary>
        [DataMember(Name = "toDate", EmitDefaultValue = false)]
        public DateTime ToDate { get; set; }

        /// <summary>
        /// Gets or Sets PaymentFilter
        /// </summary>
        [DataMember(Name = "paymentFilter", EmitDefaultValue = false)]
        public OrderPaymentFilter PaymentFilter { get; set; }

        /// <summary>
        /// Gets or Sets AgentGrn
        /// </summary>
        [DataMember(Name = "agentGrn", EmitDefaultValue = false)]
        public string AgentGrn { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedFrom
        /// </summary>
        [DataMember(Name = "updatedFrom", EmitDefaultValue = false)]
        public DateTime UpdatedFrom { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedTo
        /// </summary>
        [DataMember(Name = "updatedTo", EmitDefaultValue = false)]
        public DateTime UpdatedTo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderSearchOrdersRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  SearchQuery: ").Append(SearchQuery).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  PageToken: ").Append(PageToken).Append("\n");
            sb.Append("  OrderBy: ").Append(OrderBy).Append("\n");
            sb.Append("  StatusFilter: ").Append(StatusFilter).Append("\n");
            sb.Append("  FromDate: ").Append(FromDate).Append("\n");
            sb.Append("  ToDate: ").Append(ToDate).Append("\n");
            sb.Append("  PaymentFilter: ").Append(PaymentFilter).Append("\n");
            sb.Append("  AgentGrn: ").Append(AgentGrn).Append("\n");
            sb.Append("  UpdatedFrom: ").Append(UpdatedFrom).Append("\n");
            sb.Append("  UpdatedTo: ").Append(UpdatedTo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
