/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = order.Client.OpenAPIDateConverter;

namespace order.Model
{
    /// <summary>
    /// Defines orderPaymentAmountCode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderPaymentAmountCode
    {
        /// <summary>
        /// Enum UNKNOWN for value: UNKNOWN
        /// </summary>
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN,

        /// <summary>
        /// Enum CANCELED for value: CANCELED
        /// </summary>
        [EnumMember(Value = "CANCELED")]
        CANCELED,

        /// <summary>
        /// Enum ORDERED for value: ORDERED
        /// </summary>
        [EnumMember(Value = "ORDERED")]
        ORDERED,

        /// <summary>
        /// Enum PAID for value: PAID
        /// </summary>
        [EnumMember(Value = "PAID")]
        PAID,

        /// <summary>
        /// Enum REFUNDED for value: REFUNDED
        /// </summary>
        [EnumMember(Value = "REFUNDED")]
        REFUNDED,

        /// <summary>
        /// Enum AUTHORIZED for value: AUTHORIZED
        /// </summary>
        [EnumMember(Value = "AUTHORIZED")]
        AUTHORIZED
    }

}
