/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = order.Client.OpenAPIDateConverter;

namespace order.Model
{
    /// <summary>
    /// OrderStartFulfillmentProcessingRequest
    /// </summary>
    [DataContract(Name = "orderStartFulfillmentProcessingRequest")]
    public partial class OrderStartFulfillmentProcessingRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderStartFulfillmentProcessingRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OrderStartFulfillmentProcessingRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderStartFulfillmentProcessingRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId (required).</param>
        /// <param name="fulfillmentId">fulfillmentId (required).</param>
        public OrderStartFulfillmentProcessingRequest(string tenantId = default(string), string fulfillmentId = default(string))
        {
            // to ensure "tenantId" is required (not null)
            if (tenantId == null)
            {
                throw new ArgumentNullException("tenantId is a required property for OrderStartFulfillmentProcessingRequest and cannot be null");
            }
            this.TenantId = tenantId;
            // to ensure "fulfillmentId" is required (not null)
            if (fulfillmentId == null)
            {
                throw new ArgumentNullException("fulfillmentId is a required property for OrderStartFulfillmentProcessingRequest and cannot be null");
            }
            this.FulfillmentId = fulfillmentId;
        }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [DataMember(Name = "tenantId", IsRequired = true, EmitDefaultValue = true)]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets FulfillmentId
        /// </summary>
        [DataMember(Name = "fulfillmentId", IsRequired = true, EmitDefaultValue = true)]
        public string FulfillmentId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderStartFulfillmentProcessingRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  FulfillmentId: ").Append(FulfillmentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
