/*
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = order.Client.OpenAPIDateConverter;

namespace order.Model
{
    /// <summary>
    /// ShipmentTracking
    /// </summary>
    [DataContract(Name = "ShipmentTracking")]
    public partial class ShipmentTracking : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipmentTracking" /> class.
        /// </summary>
        /// <param name="carrierCode">carrierCode.</param>
        /// <param name="carrierTitle">carrierTitle.</param>
        /// <param name="url">url.</param>
        /// <param name="number">number.</param>
        /// <param name="labelUrl">labelUrl.</param>
        public ShipmentTracking(string carrierCode = default(string), string carrierTitle = default(string), string url = default(string), string number = default(string), string labelUrl = default(string))
        {
            this.CarrierCode = carrierCode;
            this.CarrierTitle = carrierTitle;
            this.Url = url;
            this.Number = number;
            this.LabelUrl = labelUrl;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets CarrierCode
        /// </summary>
        [DataMember(Name = "carrierCode", EmitDefaultValue = false)]
        public string CarrierCode { get; set; }

        /// <summary>
        /// Gets or Sets CarrierTitle
        /// </summary>
        [DataMember(Name = "carrierTitle", EmitDefaultValue = false)]
        public string CarrierTitle { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [DataMember(Name = "number", EmitDefaultValue = false)]
        public string Number { get; set; }

        /// <summary>
        /// Gets or Sets LabelUrl
        /// </summary>
        [DataMember(Name = "labelUrl", EmitDefaultValue = false)]
        public string LabelUrl { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShipmentTracking {\n");
            sb.Append("  CarrierCode: ").Append(CarrierCode).Append("\n");
            sb.Append("  CarrierTitle: ").Append(CarrierTitle).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  LabelUrl: ").Append(LabelUrl).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
